on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  eslint:
    name: ES Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: yarn
      - run: yarn lint
      - run: yarn type-check
